// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package test_cs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TestProtoClient is the client API for TestProto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TestProtoClient interface {
	GetValue(ctx context.Context, in *FirstValue, opts ...grpc.CallOption) (*SecondValue, error)
}

type testProtoClient struct {
	cc grpc.ClientConnInterface
}

func NewTestProtoClient(cc grpc.ClientConnInterface) TestProtoClient {
	return &testProtoClient{cc}
}

func (c *testProtoClient) GetValue(ctx context.Context, in *FirstValue, opts ...grpc.CallOption) (*SecondValue, error) {
	out := new(SecondValue)
	err := c.cc.Invoke(ctx, "/test_cs.TestProto/GetValue", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TestProtoServer is the server API for TestProto service.
// All implementations must embed UnimplementedTestProtoServer
// for forward compatibility
type TestProtoServer interface {
	GetValue(context.Context, *FirstValue) (*SecondValue, error)
	mustEmbedUnimplementedTestProtoServer()
}

// UnimplementedTestProtoServer must be embedded to have forward compatible implementations.
type UnimplementedTestProtoServer struct {
}

func (UnimplementedTestProtoServer) GetValue(context.Context, *FirstValue) (*SecondValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetValue not implemented")
}
func (UnimplementedTestProtoServer) mustEmbedUnimplementedTestProtoServer() {}

// UnsafeTestProtoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TestProtoServer will
// result in compilation errors.
type UnsafeTestProtoServer interface {
	mustEmbedUnimplementedTestProtoServer()
}

func RegisterTestProtoServer(s grpc.ServiceRegistrar, srv TestProtoServer) {
	s.RegisterService(&TestProto_ServiceDesc, srv)
}

func _TestProto_GetValue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FirstValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TestProtoServer).GetValue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/test_cs.TestProto/GetValue",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TestProtoServer).GetValue(ctx, req.(*FirstValue))
	}
	return interceptor(ctx, in, info, handler)
}

// TestProto_ServiceDesc is the grpc.ServiceDesc for TestProto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TestProto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "test_cs.TestProto",
	HandlerType: (*TestProtoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetValue",
			Handler:    _TestProto_GetValue_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}
