// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: test_gw.proto

//import "google/api/annotations.proto";

package test_gw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FirstValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val1 int32 `protobuf:"varint,1,opt,name=val1,proto3" json:"val1,omitempty"`
	Val2 int32 `protobuf:"varint,2,opt,name=val2,proto3" json:"val2,omitempty"`
}

func (x *FirstValue) Reset() {
	*x = FirstValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_gw_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FirstValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FirstValue) ProtoMessage() {}

func (x *FirstValue) ProtoReflect() protoreflect.Message {
	mi := &file_test_gw_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FirstValue.ProtoReflect.Descriptor instead.
func (*FirstValue) Descriptor() ([]byte, []int) {
	return file_test_gw_proto_rawDescGZIP(), []int{0}
}

func (x *FirstValue) GetVal1() int32 {
	if x != nil {
		return x.Val1
	}
	return 0
}

func (x *FirstValue) GetVal2() int32 {
	if x != nil {
		return x.Val2
	}
	return 0
}

type SecondValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Val3 int32 `protobuf:"varint,1,opt,name=val3,proto3" json:"val3,omitempty"`
	Val4 int32 `protobuf:"varint,2,opt,name=val4,proto3" json:"val4,omitempty"`
}

func (x *SecondValue) Reset() {
	*x = SecondValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_test_gw_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SecondValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecondValue) ProtoMessage() {}

func (x *SecondValue) ProtoReflect() protoreflect.Message {
	mi := &file_test_gw_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SecondValue.ProtoReflect.Descriptor instead.
func (*SecondValue) Descriptor() ([]byte, []int) {
	return file_test_gw_proto_rawDescGZIP(), []int{1}
}

func (x *SecondValue) GetVal3() int32 {
	if x != nil {
		return x.Val3
	}
	return 0
}

func (x *SecondValue) GetVal4() int32 {
	if x != nil {
		return x.Val4
	}
	return 0
}

var File_test_gw_proto protoreflect.FileDescriptor

var file_test_gw_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x07, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x77, 0x22, 0x34, 0x0a, 0x0a, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x31, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x31, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61,
	0x6c, 0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x61, 0x6c, 0x32, 0x22, 0x35,
	0x0a, 0x0b, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x76, 0x61, 0x6c, 0x33, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x76, 0x61, 0x6c,
	0x33, 0x12, 0x12, 0x0a, 0x04, 0x76, 0x61, 0x6c, 0x34, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x76, 0x61, 0x6c, 0x34, 0x32, 0xca, 0x01, 0x0a, 0x09, 0x54, 0x65, 0x73, 0x74, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x37, 0x0a, 0x08, 0x47, 0x65, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12,
	0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x77, 0x2e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x56,
	0x61, 0x6c, 0x75, 0x65, 0x1a, 0x14, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x77, 0x2e, 0x53,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x12, 0x3f, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x13,
	0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x77, 0x2e, 0x46, 0x69, 0x72, 0x73, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x1a, 0x14, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x77, 0x2e, 0x53, 0x65,
	0x63, 0x6f, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x30, 0x01, 0x12, 0x43, 0x0a,
	0x10, 0x47, 0x65, 0x74, 0x42, 0x69, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x13, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x77, 0x2e, 0x46, 0x69, 0x72, 0x73,
	0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x14, 0x2e, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x77,
	0x2e, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x00, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x13, 0x5a, 0x11, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x74, 0x65, 0x73, 0x74, 0x5f, 0x67, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_test_gw_proto_rawDescOnce sync.Once
	file_test_gw_proto_rawDescData = file_test_gw_proto_rawDesc
)

func file_test_gw_proto_rawDescGZIP() []byte {
	file_test_gw_proto_rawDescOnce.Do(func() {
		file_test_gw_proto_rawDescData = protoimpl.X.CompressGZIP(file_test_gw_proto_rawDescData)
	})
	return file_test_gw_proto_rawDescData
}

var file_test_gw_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_test_gw_proto_goTypes = []interface{}{
	(*FirstValue)(nil),  // 0: test_gw.FirstValue
	(*SecondValue)(nil), // 1: test_gw.SecondValue
}
var file_test_gw_proto_depIdxs = []int32{
	0, // 0: test_gw.TestProto.GetValue:input_type -> test_gw.FirstValue
	0, // 1: test_gw.TestProto.GetStreamValue:input_type -> test_gw.FirstValue
	0, // 2: test_gw.TestProto.GetBiStreamValue:input_type -> test_gw.FirstValue
	1, // 3: test_gw.TestProto.GetValue:output_type -> test_gw.SecondValue
	1, // 4: test_gw.TestProto.GetStreamValue:output_type -> test_gw.SecondValue
	1, // 5: test_gw.TestProto.GetBiStreamValue:output_type -> test_gw.SecondValue
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_test_gw_proto_init() }
func file_test_gw_proto_init() {
	if File_test_gw_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_test_gw_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FirstValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_test_gw_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SecondValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_test_gw_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_test_gw_proto_goTypes,
		DependencyIndexes: file_test_gw_proto_depIdxs,
		MessageInfos:      file_test_gw_proto_msgTypes,
	}.Build()
	File_test_gw_proto = out.File
	file_test_gw_proto_rawDesc = nil
	file_test_gw_proto_goTypes = nil
	file_test_gw_proto_depIdxs = nil
}
